[package]
name = "uuuh"
version = "0.1.0"
authors = ["Daniel <dabass2@illinois.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"